######################################################################
# Automatically generated by qmake (2.01a) Do 30. Aug 20:18:52 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

win32 {
# Input
HEADERS += ds_videodevice.h ds_utils.h
SOURCES += ds_videodevice.cpp dsmain.cpp
}

unix:!macx {

CXX_FLAGS += --std=c++11

HEADERS += v4l_device.h
SOURCES += v4l_device.cpp main.cpp

QMAKE_LIBS += -lv4l2
}

